name: tests
on: [push]
jobs:
  build:
    name: build
    runs-on: [ubuntu-latest]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2.2.0
      with:
        go-version: 1.17
      id: go

    - name: Checkout git repository
      uses: actions/checkout@v3.0.1

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test ./...
